### ISSUE TITLE
[BUG] Exception in server tick loop when interacting with ModularWorkbench 

### ISSUE THREAD

**Issue by Sanlovty** [AMPZNetwork/All-The-Fabric#4]
## Bug Description
Exception in server tick loop when interacting with ModularWorkbench on my server.
I found that `indrez-1.16.5-BETA-Hotfix` used in all the fabric is custom rework on `inrev-1.16.5-Beta` to work with newset 15.9 fabric loader.  Firstly, faced with this crash i thought `Time and Wind` can be the issue but no, removing and testing on another server doesnt affects somehow. Than i tried to use `inrev-1.16.5-Beta` on server without all time fabric and it worked. My conclussion that the issue is in customed mod indrez. Hope u can help. Im also able to give u any info u need. I also found out that others are too facing with this problem ( https://github.com/GabrielOlvH/Industrial-Revolution/issues/578) but i think the author of indrev has nothing to do with indrez custom

## Reproduction Steps
- Install `minecraft_server.1.20.1.jar`
- Install `fabric-server-mc.1.20.1-loader.0.15.9-launcher.1.0.1.jar` from fabric officical website
- Add `indrez-1.16.5-BETA-Hotfix.jar` from AllTheFabric modpack
- Start server
- Place ModularWorkbench
- Right click on it

## Expected Outcome
Server crash 

## Crash Log (if applicable)
[crash-2024-04-14_00.32.11-server.txt](https://github.com/AMPZNetwork/All-The-Fabric/files/14968840/crash-2024-04-14_00.32.11-server.txt)

Updated with 5.6 and fully clear server: 
[crash-2024-04-14_15.35.59-server.txt](https://github.com/AMPZNetwork/All-The-Fabric/files/14970767/crash-2024-04-14_15.35.59-server.txt)

## Screenshots
no 

## Basic Information (please fill in the following details):
 - Operating System: Linux
 - All The Fabric v5.5 / 5.6
 - Platform: ATLauncher
 - Additional Mods Installed: Time and Wind / Nothing

**Comment by LabsZero** [comment]
Fixed in upcoming 5.6.1. Thanks for you help.
