### ISSUE TITLE
[BUG] Missing or Bugged Textures for Plate Armor

### ISSUE THREAD

**Issue by aechtc** [AMPZNetwork/All-The-Fabric#7]
## Bug Description
Missing or bugged duplicate textures observed for plated armor.

## Reproduction Steps 
To replicate the problem, follow these steps:
Bugged Textures:
1. Navigate to 'REI config'
2. Search '@hephaestus plate armor'
3. Observe the error: all plate armor have same texture (chestplate)

Missing Textures:
1. Craft 'Encyclopedia of Tinkering'
2. Navigate to first page
3. Observe the error: Armor texture is blank

## Expected Outcome
Bugged: Textures of plate armor should be different from each piece 
Missing: Textures of plate armor in book should be observed

## Crash Log (if applicable)
N/A

## Screenshots
![image](https://github.com/user-attachments/assets/76e19733-d49b-4d0e-8051-daef05004630)
![image](https://github.com/user-attachments/assets/5c7e0fff-fe2e-4ca9-9420-3c5dc83d6d43)
![image](https://github.com/user-attachments/assets/bf1f800c-969d-4d85-bc0c-090a5aa35bec)
![image](https://github.com/user-attachments/assets/5f465bcb-a3d1-4f80-9896-3a3e08ba1d3f)

## Basic Information:
 - Operating System: Windows 10
 - All The Fabric Version: [e.g., v5.10.0]
 - Platform: Modrinth
 - Additional Mods Installed: N/A

**Comment by LabsZero** [comment]
Your going to have to report this to the dev for them to resolve.

Their github: https://github.com/Alpha-s-Stuff/TinkersConstruct/issues
